### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by tencek** [Q-Minh/EventStore.Client.Api.Cpp#10]
Hi, thank you for C++ client API to EventStore, I like it!

I'd like to use it but there's no license included so [I can't](https://choosealicense.com/no-permission/), for now.

Could you please add some license so one can use it legally? I suggest using some permissive license, e.g.
- [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/)
- [MIT License](https://choosealicense.com/licenses/mit/)

**Comment by tencek** [comment]
Licenses of your dependencies:
- Protobuf - https://github.com/google/protobuf/blob/master/LICENSE
- Boost - https://www.boost.org/LICENSE_1_0.txt - Boost Software License
- Catch2 - https://github.com/catchorg/Catch2/blob/master/LICENSE.txt - Boost Software License
- spdlog - https://github.com/gabime/spdlog/blob/v1.x/LICENSE - MIT
- nlohmann-json - https://github.com/nlohmann/json/blob/develop/LICENSE.MIT - MIT

**Comment by Q-Minh** [comment]
Yes, definitely. I hadn't touched on the project for a while and it wasn't exactly complete, but I can definitely add a permissive license. It will be done before the end of the day.

**Comment by Q-Minh** [comment]
I've added the license at the root of the repository. Is this enough for legal usage?

**Comment by tencek** [comment]
Yes, I believe so, thank you!
